---
version: "3"
services:
  node:
    build:
      context: .
      args:
        - arch=${ARCH:-x86_64}
    command: ./setup_and_run.sh wavehash18ak4mdzl8cj0rlczdhrctryrjq52gvqucven28
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
    environment:
      - GAS_LIMIT=${GAS_LIMIT:-10000000}
      - STAKE_TOKEN=${STAKE_TOKEN:-uwahax}
      - TIMEOUT_COMMIT=${TIMEOUT_COMMIT:-5s}
